pipeline {
    agent { label 'slave' }

    options {
        timestamps()
    }
    stages {
        stage('Unit tests'){
            steps {
                echo 'unit tests ...'                
            }
            post {            
                always {
				          echo "Goodbye!"
                }
            }
        }     
    }
}
